## Ноутбук 02: EDA и предобработка отзывов пользователей (Reviews)
### Цели и задачи исследования:
1. **Очистка данных и валидация типов:** Проверка пропусков, дубликатов, обработка временных полей (`timestamp_created` -> `datetime`) и валидация структурных аномалий.
2. **Анализ распределения взаимодействий (EDA):** Исследование активности пользователей (User Degree), популярности игр (Item Degree) и общей разреженности графа взаимодействий (Sparsity).
3. **Формирование сигнала увлеченности:** Анализ распределения времени игры (`playtime_forever`) и его логарифмирование ($\log(1 + \text{playtime})$) для создания взвешенного фидбека.
4. **Сохранение подготовленного датасета:** Экспорт очищенной базовой таблицы в формат `reviews_clean.parquet`.

In [1]:
import polars as pl
import os
from tqdm import tqdm
import matplotlib.pyplot as plt
import seaborn as sns

pl.Config.set_tbl_cols(-1)

data_dir = '../data'
output_dir = '../data/processed'

### Загрузка и общая структура данных

In [2]:
reviews_df = pl.read_csv(
    os.path.join(data_dir, 'reviews.csv'),
    ignore_errors=True
)

reviews_df.head(3)

shape: (3, 23)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ rec ┆ app ┆ aut ┆ aut ┆ aut ┆ aut ┆ aut ┆ aut ┆ aut ┆ lan ┆ rev ┆ tim ┆ tim ┆ vot ┆ vot ┆ vot ┆ wei ┆ com ┆ ste ┆ rec ┆ wri ┆ cre ┆ upd │
│ omm ┆ id  ┆ hor ┆ hor ┆ hor ┆ hor ┆ hor ┆ hor ┆ hor ┆ gua ┆ iew ┆ est ┆ est ┆ ed_ ┆ es_ ┆ es_ ┆ ght ┆ men ┆ am_ ┆ eiv ┆ tte ┆ ate ┆ ate │
│ end ┆ --- ┆ _st ┆ _nu ┆ _nu ┆ _pl ┆ _pl ┆ _pl ┆ _la ┆ ge  ┆ _te ┆ amp ┆ amp ┆ up  ┆ up  ┆ fun ┆ ed_ ┆ t_c ┆ pur ┆ ed_ ┆ n_d ┆ d_a ┆ d_a │
│ ati ┆ i64 ┆ eam ┆ m_g ┆ m_r ┆ ayt ┆ ayt ┆ ayt ┆ st_ ┆ --- ┆ xt  ┆ _cr ┆ _up ┆ --- ┆ --- ┆ ny  ┆ vot ┆ oun ┆ cha ┆ for ┆ uri ┆ t   ┆ t   │
│ oni ┆     ┆ id  ┆ ame ┆ evi ┆ ime ┆ ime ┆ ime ┆ pla ┆ str ┆ --- ┆ eat ┆ dat ┆ boo ┆ i64 ┆ --- ┆ e_s ┆ t   ┆ se  ┆ _fr ┆ ng_ ┆ --- ┆ --- │
│ d   ┆     ┆ --- ┆ s_o ┆ ews ┆ _fo ┆ _la ┆ _at ┆ yed ┆     ┆ str ┆ ed  ┆ ed  ┆ l   ┆     ┆ i64 ┆ cor ┆ --- ┆ --- ┆ ee  ┆ ear ┆ str ┆ str │
│ --- ┆     ┆ i64 ┆ wne ┆ --- ┆ rev ┆ st_ ┆ _re ┆ --- ┆     ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆ e   ┆ i64 ┆ boo ┆ --- ┆ ly_ ┆     ┆     │
│ i64 ┆     ┆     ┆ d   ┆ i64 ┆ er  ┆ two ┆ vie ┆ i64 ┆     ┆     ┆ i64 ┆ i64 ┆     ┆     ┆     ┆ --- ┆     ┆ l   ┆ boo ┆ acc ┆     ┆     │
│     ┆     ┆     ┆ --- ┆     ┆ --- ┆ _we ┆ w   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆ l   ┆ ess ┆     ┆     │
│     ┆     ┆     ┆ i64 ┆     ┆ i64 ┆ eks ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ boo ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 100 ┆ 264 ┆ 765 ┆ 760 ┆ 74  ┆ 12  ┆ 0   ┆ 12. ┆ 139 ┆ pol ┆ Wha ┆ 139 ┆ 139 ┆ tru ┆ 0   ┆ 1   ┆ 0.4 ┆ 0   ┆ tru ┆ fal ┆ fal ┆ 202 ┆ 202 │
│ 000 ┆ 220 ┆ 611 ┆     ┆     ┆     ┆     ┆ 0   ┆ 905 ┆ ish ┆ t's ┆ 905 ┆ 905 ┆ e   ┆     ┆     ┆ 599 ┆     ┆ e   ┆ se  ┆ se  ┆ 5-0 ┆ 5-0 │
│ 00  ┆     ┆ 980 ┆     ┆     ┆     ┆     ┆     ┆ 957 ┆     ┆ a   ┆ 996 ┆ 996 ┆     ┆     ┆     ┆ 06  ┆     ┆     ┆     ┆     ┆ 9-0 ┆ 9-0 │
│     ┆     ┆ 854 ┆     ┆     ┆     ┆     ┆     ┆ 3   ┆     ┆ cra ┆ 5   ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7   ┆ 8   │
│     ┆     ┆ 058 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ p.  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 12: ┆ 00: │
│     ┆     ┆ 44  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Thi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 51: ┆ 47: │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00. ┆ 55. │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ gam ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 564 ┆ 754 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 782 ┆ 043 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cos ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ +00 ┆ +00 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ts… ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ :…  ┆ :…  │
│ 100 ┆ 100 ┆ 765 ┆ 485 ┆ 234 ┆ 424 ┆ 0   ┆ 424 ┆ 163 ┆ rus ┆ Игр ┆ 163 ┆ 163 ┆ tru ┆ 8   ┆ 0   ┆ 0.6 ┆ 0   ┆ tru ┆ fal ┆ fal ┆ 202 ┆ 202 │
│ 001 ┆ 644 ┆ 611 ┆     ┆     ┆     ┆     ┆ .0  ┆ 266 ┆ sia ┆ а в ┆ 267 ┆ 267 ┆ e   ┆     ┆     ┆ 307 ┆     ┆ e   ┆ se  ┆ se  ┆ 5-0 ┆ 5-0 │
│ 066 ┆ 0   ┆ 980 ┆     ┆     ┆     ┆     ┆     ┆ 641 ┆ n   ┆ жан ┆ 399 ┆ 399 ┆     ┆     ┆     ┆ 7   ┆     ┆     ┆     ┆     ┆ 9-0 ┆ 9-0 │
│     ┆     ┆ 144 ┆     ┆     ┆     ┆     ┆     ┆ 7   ┆     ┆ ре  ┆ 2   ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7   ┆ 8   │
│     ┆     ┆ 398 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ кве ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 12: ┆ 00: │
│     ┆     ┆ 59  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ста ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 51: ┆ 47: │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ poi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00. ┆ 55. │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nt- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 564 ┆ 754 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ &-c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 782 ┆ 043 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l…  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ +00 ┆ +00 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ :…  ┆ :…  │
│ 100 ┆ 320 ┆ 765 ┆ 0   ┆ 385 ┆ 0   ┆ 0   ┆ nul ┆ 0   ┆ ger ┆ Ern ┆ 163 ┆ 163 ┆ fal ┆ 1   ┆ 0   ┆ 0.5 ┆ 0   ┆ tru ┆ fal ┆ fal ┆ 202 ┆ 202 │
│ 002 ┆ 721 ┆ 611 ┆     ┆     ┆     ┆     ┆ l   ┆     ┆ man ┆ eut ┆ 267 ┆ 267 ┆ se  ┆     ┆     ┆ 238 ┆     ┆ e   ┆ se  ┆ se  ┆ 5-0 ┆ 5-0 │
│ 344 ┆     ┆ 980 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ gib ┆ 563 ┆ 563 ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆ 9-0 ┆ 9-0 │
│     ┆     ┆ 480 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ t   ┆ 1   ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7   ┆ 8   │
│     ┆     ┆ 385 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 12: ┆ 00: │
│     ┆     ┆ 90  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ein ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 51: ┆ 47: │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ en  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00. ┆ 55. │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ DLC ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 564 ┆ 754 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 782 ┆ 043 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ d…  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ +00 ┆ +00 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ :…  ┆ :…  │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

In [3]:
reviews_df.glimpse()

Rows: 1048148
Columns: 23
$ recommendationid                <i64> 10000000, 100001066, 100002344, 100002361, 100002504, 100002591, 100003580, 100003676, 100003804, 100005000
$ appid                           <i64> 264220, 1006440, 320721, 1604700, 1338560, 1418320, 1232500, 726870, 1721670, 1638870
$ author_steamid                  <i64> 76561198085405844, 76561198014439859, 76561198048038590, 76561197994386273, 76561198138996331, 76561199208288640, 76561199089236340, 76561198155272674, 76561198056175175, 76561199059802534
$ author_num_games_owned          <i64> 760, 485, 0, 0, 816, 0, 0, 0, 315, 0
$ author_num_reviews              <i64> 74, 234, 385, 3, 26, 1, 2, 13, 14, 4
$ author_playtime_forever         <i64> 12, 424, 0, 86, 25, 60, 311, 639, 0, 12
$ author_playtime_last_two_weeks  <i64> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
$ author_playtime_at_review       <f64> 12.0, 424.0, null, 86.0, 25.0, 60.0, 261.0, 188.0, null, 12.0
$ author_last_played              <i64> 1399059573, 1632666417, 0, 1632674318, 1632639242, 1631962286, 1728524073, 1632773037, 0, 1630245355
$ language                        <str> 'polish', 'russian', 'german', 'english', 'english', 'spanish', 'japanese', 'english', 'english', 'russian'
$ review_text                     <str> "What's a crap. This game costs 2 euro but is worth less than 0.1 cent. It has full of bugs, is slowly, not dynamic. It's crashed under my windows xp, so I installed on win8.1, it's crashed too. Please test it before you release.", 'Игра в жанре квеста point-&-click, но особенность в том, что вся игра отснята с живыми актёрами в реальном окружении. Вы частный детектив и в один из обычных рутинных дней к вам приходит дама с просьбой. И понеслось. Мотаешься по всему городу, общаешься с людьми, добываешь информацию и всё в заранее отснятых сценах. Где-то более часа чистого видео материала на все ваше действия, правильные и ошибочные.', 'Erneut gibt es einen DLC mit drei neuen Lords die sich nur maginal von den anderen unterscheiden. Für (momentan) fünf Euro finde ich das persönlich etwas zu viel.', 'It took me a grueling 18 months, but I built a catalog of more than 30 highly-regarded books and raised our average first print revenue to nearly a million dollars.\n\nA completely authentic publishing sim.', "incredibly simple game. it does get boring quite quickly and there isn't much to do in this game. it's not really worth $1 though. It's a good game to have playing in the background while you study though. \n\nCats also enjoy watching the bees fly around your screen. 10/10 for that.", 'Un juego entretenido que he regalado a mis sobrinos de 10 y 12 años  y les ha encantado. Un mundo, el del Siglo de Oro español, desconocido para ellos, que ha permitido que al menos me hagan algunas preguntas sobre Don Quijote.', '一言で言うと2か所のチェックポイントを通過し、ゴールを目指すゲーム。\nなんでライフルを持ってるのって？山は危険だからね護身武器は必要だよね（棒読み）\n\n高難度の方までクリアしましたが、慎重に進めば時間はかかりますけど\nやられることはないと思います。リンが回復してくれますし。\n敵は奥から来るだけでなく崖の上にいることもあるので注意。\n\nハイキングってなんだ（哲学）\n自分は割と楽しんだのでおすすめしておきます。', 'If you enjoy text-based games, this is a must buy -- particularly if you like horror, sleuthing, and/or the Cthulhu mythos.  \n\nFor older gamers, note that this game is as good as (and in some respects even better than) many classic Infocom interactive fiction titles.', 'very cool.', 'ДИЧЬ\n'
$ timestamp_created               <i64> 1399059965, 1632673992, 1632675631, 1632675648, 1632675819, 1632675927, 1632677169, 1632677314, 1632677489, 1632678961
$ timestamp_updated               <i64> 1399059965, 1632673992, 1632675631, 1632680067, 1632675819, 1632675927, 1632677169, 1639239547, 1632677489, 1632678961
$ voted_up                       <bool> True, True, False, True, True, True, True, True, True, False
$ votes_up                        <i64> 0, 8, 1, 3, 1, 2, 2, 0, 0, 0
$ votes_funny                     <i64> 1, 0, 0, 0, 0, 0, 0, 0, 0, 0
$ weighted_vote_score             <f64> 0.45990565, 0.63077044, 0.52380955, 0.54198474, 0.52380955, 0.54545456, 0.54038996, 0.5, 0.5, 0.5
$ comment_count                   <i64> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
$ steam_purchase                 <bool> True, True, True, True, True, True, True, True, True, True
$ received_for_free              <bool> False, False, False, False, False, False, False, False, False, False
$ written_during_early_access    <bool> False, False, False, False, False, False, False, False, False, False
$ created_at                      <str> '2025-09-07 12:51:00.564782+00:00', '2025-09-07 12:51:00.564782+00:00', '2025-09-07 12:51:00.564782+00:00', '2025-09-07 12:51:00.564782+00:00', '2025-09-07 12:51:00.564782+00:00', '2025-09-07 12:51:00.564782+00:00', '2025-09-07 12:51:00.564782+00:00', '2025-09-07 12:51:00.564782+00:00', '2025-09-07 12:51:00.564782+00:00', '2025-09-07 12:51:00.564782+00:00'
$ updated_at                      <str> '2025-09-08 00:47:55.754043+00:00', '2025-09-08 00:47:55.754043+00:00', '2025-09-08 00:47:55.754043+00:00', '2025-09-08 00:47:55.754043+00:00', '2025-09-08 00:47:55.754043+00:00', '2025-09-08 00:47:55.754043+00:00', '2025-09-08 00:47:55.754043+00:00', '2025-09-08 00:47:55.754043+00:00', '2025-09-08 00:47:55.754043+00:00', '2025-09-08 00:47:55.754043+00:00'

In [4]:
reviews_df.null_count()

shape: (1, 23)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ rec ┆ app ┆ aut ┆ aut ┆ aut ┆ aut ┆ aut ┆ aut ┆ aut ┆ lan ┆ rev ┆ tim ┆ tim ┆ vot ┆ vot ┆ vot ┆ wei ┆ com ┆ ste ┆ rec ┆ wri ┆ cre ┆ upd │
│ omm ┆ id  ┆ hor ┆ hor ┆ hor ┆ hor ┆ hor ┆ hor ┆ hor ┆ gua ┆ iew ┆ est ┆ est ┆ ed_ ┆ es_ ┆ es_ ┆ ght ┆ men ┆ am_ ┆ eiv ┆ tte ┆ ate ┆ ate │
│ end ┆ --- ┆ _st ┆ _nu ┆ _nu ┆ _pl ┆ _pl ┆ _pl ┆ _la ┆ ge  ┆ _te ┆ amp ┆ amp ┆ up  ┆ up  ┆ fun ┆ ed_ ┆ t_c ┆ pur ┆ ed_ ┆ n_d ┆ d_a ┆ d_a │
│ ati ┆ u32 ┆ eam ┆ m_g ┆ m_r ┆ ayt ┆ ayt ┆ ayt ┆ st_ ┆ --- ┆ xt  ┆ _cr ┆ _up ┆ --- ┆ --- ┆ ny  ┆ vot ┆ oun ┆ cha ┆ for ┆ uri ┆ t   ┆ t   │
│ oni ┆     ┆ id  ┆ ame ┆ evi ┆ ime ┆ ime ┆ ime ┆ pla ┆ u32 ┆ --- ┆ eat ┆ dat ┆ u32 ┆ u32 ┆ --- ┆ e_s ┆ t   ┆ se  ┆ _fr ┆ ng_ ┆ --- ┆ --- │
│ d   ┆     ┆ --- ┆ s_o ┆ ews ┆ _fo ┆ _la ┆ _at ┆ yed ┆     ┆ u32 ┆ ed  ┆ ed  ┆     ┆     ┆ u32 ┆ cor ┆ --- ┆ --- ┆ ee  ┆ ear ┆ u32 ┆ u32 │
│ --- ┆     ┆ u32 ┆ wne ┆ --- ┆ rev ┆ st_ ┆ _re ┆ --- ┆     ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆ e   ┆ u32 ┆ u32 ┆ --- ┆ ly_ ┆     ┆     │
│ u32 ┆     ┆     ┆ d   ┆ u32 ┆ er  ┆ two ┆ vie ┆ u32 ┆     ┆     ┆ u32 ┆ u32 ┆     ┆     ┆     ┆ --- ┆     ┆     ┆ u32 ┆ acc ┆     ┆     │
│     ┆     ┆     ┆ --- ┆     ┆ --- ┆ _we ┆ w   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆     ┆     ┆     ┆ ess ┆     ┆     │
│     ┆     ┆     ┆ u32 ┆     ┆ u32 ┆ eks ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ u32 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 981 ┆ 981 ┆ 178 ┆ 981 ┆ 0   ┆ 769 ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   │
│     ┆     ┆     ┆     ┆     ┆ 48  ┆ 48  ┆ 857 ┆ 48  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

### Качество данных

Проверка на дубликаты:

In [5]:
full_duplicates = reviews_df.is_duplicated().sum()
print(f"Полных дубликатов: {full_duplicates}")

user_item_duplicates = (reviews_df
    .group_by(['author_steamid', 'appid'])
    .len()
    .filter(pl.col('len') > 1)
)
print(f"Уникальных user-item пар с повторениями: {len(user_item_duplicates)}")
print(f"Всего лишних записей в повторных user-item парах: {(user_item_duplicates['len'] - 1).sum()}")

invalid_user_ids = reviews_df.filter(
    pl.col("author_steamid").is_null() |
    (pl.col("author_steamid") <= 0)
)
invalid_game_ids = reviews_df.filter(
    pl.col("appid").is_null() |
    (pl.col("appid") <= 0)
)
print(f"Некорректных user_id: {len(invalid_user_ids)}")
print(f"Некорректных appid: {len(invalid_game_ids)}")


invalid_playtime = reviews_df.filter(
    pl.col("author_playtime_forever").is_null() |
    (pl.col("author_playtime_forever") < 0)
)
print(f"Некорректных значений playtime: {len(invalid_playtime)}")

Полных дубликатов: 0
Уникальных user-item пар с повторениями: 6
Всего лишних записей в повторных user-item парах: 8
Некорректных user_id: 0
Некорректных appid: 0
Некорректных значений playtime: 98148

Проанализируем user-item дубликаты:

In [6]:
duplicates = reviews_df.join(user_item_duplicates, on=['author_steamid', 'appid'], how='semi')
duplicates

shape: (14, 23)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ rec ┆ app ┆ aut ┆ aut ┆ aut ┆ aut ┆ aut ┆ aut ┆ aut ┆ lan ┆ rev ┆ tim ┆ tim ┆ vot ┆ vot ┆ vot ┆ wei ┆ com ┆ ste ┆ rec ┆ wri ┆ cre ┆ upd │
│ omm ┆ id  ┆ hor ┆ hor ┆ hor ┆ hor ┆ hor ┆ hor ┆ hor ┆ gua ┆ iew ┆ est ┆ est ┆ ed_ ┆ es_ ┆ es_ ┆ ght ┆ men ┆ am_ ┆ eiv ┆ tte ┆ ate ┆ ate │
│ end ┆ --- ┆ _st ┆ _nu ┆ _nu ┆ _pl ┆ _pl ┆ _pl ┆ _la ┆ ge  ┆ _te ┆ amp ┆ amp ┆ up  ┆ up  ┆ fun ┆ ed_ ┆ t_c ┆ pur ┆ ed_ ┆ n_d ┆ d_a ┆ d_a │
│ ati ┆ i64 ┆ eam ┆ m_g ┆ m_r ┆ ayt ┆ ayt ┆ ayt ┆ st_ ┆ --- ┆ xt  ┆ _cr ┆ _up ┆ --- ┆ --- ┆ ny  ┆ vot ┆ oun ┆ cha ┆ for ┆ uri ┆ t   ┆ t   │
│ oni ┆     ┆ id  ┆ ame ┆ evi ┆ ime ┆ ime ┆ ime ┆ pla ┆ str ┆ --- ┆ eat ┆ dat ┆ boo ┆ i64 ┆ --- ┆ e_s ┆ t   ┆ se  ┆ _fr ┆ ng_ ┆ --- ┆ --- │
│ d   ┆     ┆ --- ┆ s_o ┆ ews ┆ _fo ┆ _la ┆ _at ┆ yed ┆     ┆ str ┆ ed  ┆ ed  ┆ l   ┆     ┆ i64 ┆ cor ┆ --- ┆ --- ┆ ee  ┆ ear ┆ str ┆ str │
│ --- ┆     ┆ i64 ┆ wne ┆ --- ┆ rev ┆ st_ ┆ _re ┆ --- ┆     ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆ e   ┆ i64 ┆ boo ┆ --- ┆ ly_ ┆     ┆     │
│ i64 ┆     ┆     ┆ d   ┆ i64 ┆ er  ┆ two ┆ vie ┆ i64 ┆     ┆     ┆ i64 ┆ i64 ┆     ┆     ┆     ┆ --- ┆     ┆ l   ┆ boo ┆ acc ┆     ┆     │
│     ┆     ┆     ┆ --- ┆     ┆ --- ┆ _we ┆ w   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆ l   ┆ ess ┆     ┆     │
│     ┆     ┆     ┆ i64 ┆     ┆ i64 ┆ eks ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ boo ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 103 ┆ 207 ┆ 765 ┆ 50  ┆ 1   ┆ 68  ┆ 0   ┆ 68. ┆ 140 ┆ rus ┆ да  ┆ 140 ┆ 140 ┆ tru ┆ 0   ┆ 0   ┆ 0.5 ┆ 0   ┆ tru ┆ fal ┆ fal ┆ 202 ┆ 202 │
│ 436 ┆ 000 ┆ 611 ┆     ┆     ┆     ┆     ┆ 0   ┆ 214 ┆ sia ┆ игр ┆ 188 ┆ 188 ┆ e   ┆     ┆     ┆     ┆     ┆ e   ┆ se  ┆ se  ┆ 5-0 ┆ 5-0 │
│ 95  ┆     ┆ 981 ┆     ┆     ┆     ┆     ┆     ┆ 429 ┆ n   ┆ а   ┆ 369 ┆ 369 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9-0 ┆ 9-0 │
│     ┆     ┆ 341 ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆ хор ┆ 2   ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7   ┆ 9   │
│     ┆     ┆ 725 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ оша ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 12: ┆ 00: │
│     ┆     ┆ 48  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ я   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 51: ┆ 57: │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ но  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00. ┆ 00. │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ раз ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 564 ┆ 523 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ова ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 782 ┆ 312 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ я   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ +00 ┆ +00 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ :…  ┆ :…  │
│ 103 ┆ 207 ┆ 765 ┆ 50  ┆ 1   ┆ 68  ┆ 0   ┆ 68. ┆ 140 ┆ rus ┆ да  ┆ 140 ┆ 140 ┆ tru ┆ 0   ┆ 0   ┆ 0.5 ┆ 0   ┆ tru ┆ fal ┆ fal ┆ 202 ┆ 202 │
│ 436 ┆ 000 ┆ 611 ┆     ┆     ┆     ┆     ┆ 0   ┆ 214 ┆ sia ┆ игр ┆ 188 ┆ 188 ┆ e   ┆     ┆     ┆     ┆     ┆ e   ┆ se  ┆ se  ┆ 5-0 ┆ 5-0 │
│ 96  ┆     ┆ 981 ┆     ┆     ┆     ┆     ┆     ┆ 429 ┆ n   ┆ а   ┆ 369 ┆ 369 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9-0 ┆ 9-0 │
│     ┆     ┆ 341 ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆ хор ┆ 2   ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7   ┆ 9   │
│     ┆     ┆ 725 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ оша ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 12: ┆ 00: │
│     ┆     ┆ 48  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ я   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 51: ┆ 57: │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ но  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00. ┆ 00. │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ раз ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 564 ┆ 523 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ова ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 782 ┆ 312 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ я   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ +00 ┆ +00 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ :…  ┆ :…  │
│ 103 ┆ 253 ┆ 765 ┆ 0   ┆ 1   ┆ 68  ┆ 0   ┆ 64. ┆ 140 ┆ eng ┆ Gre ┆ 140 ┆ 140 ┆ tru ┆ 11  ┆ 0   ┆ 0.5 ┆ 3   ┆ tru ┆ fal ┆ fal ┆ 202 ┆ 202 │
│ 453 ┆ 370 ┆ 611 ┆     ┆     ┆     ┆     ┆ 0   ┆ 249 ┆ lis ┆ at  ┆ 189 ┆ 189 ┆ e   ┆     ┆     ┆ 131 ┆     ┆ e   ┆ se  ┆ se  ┆ 5-0 ┆ 5-0 │
│ 10  ┆     ┆ 980 ┆     ┆     ┆     ┆     ┆     ┆ 567 ┆ h   ┆ for ┆ 580 ┆ 580 ┆     ┆     ┆     ┆ 39  ┆     ┆     ┆     ┆     ┆ 9-0 ┆ 9-0 │
│     ┆     ┆ 692 ┆     ┆     ┆     ┆     ┆     ┆ 3   ┆     ┆ beg ┆ 9   ┆ 9   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7   ┆ 9   │
│     ┆     ┆ 443 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ inn ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 12: ┆ 00: │
│     ┆     ┆ 36  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ers ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 51: ┆ 57: │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ in  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00. ┆ 00. │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ des ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 564 ┆ 523 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ign ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 782 ┆ 312 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i…  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ +00 ┆ +00 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ :…  ┆ :…  │
│ 103 ┆ 253 ┆ 765 ┆ 0   ┆ 1   ┆ 68  ┆ 0   ┆ 64. ┆ 140 ┆ eng ┆ Gre ┆ 140 ┆ 140 ┆ tru ┆ 12  ┆ 0   ┆ 0.4 ┆ 0   ┆ tru ┆ fal ┆ fal ┆ 202 ┆ 202 │
│ 453 ┆ 370 ┆ 611 ┆     ┆     ┆     ┆     ┆ 0   ┆ 249 ┆ lis ┆ at  ┆ 189 ┆ 189 ┆ e   ┆     ┆     ┆ 882 ┆     ┆ e   ┆ se  ┆ se  ┆ 5-0 ┆ 5-0 │
│ 11  ┆     ┆ 980 ┆     ┆     ┆     ┆     ┆     ┆ 567 ┆ h   ┆ for ┆ 580 ┆ 580 ┆     ┆     ┆     ┆ 08  ┆     ┆     ┆     ┆     ┆ 9-0 ┆ 9-0 │
│     ┆     ┆ 692 ┆     ┆     ┆     ┆     ┆     ┆ 3   ┆     ┆ beg ┆ 9   ┆ 9   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7   ┆ 9   │
│     ┆     ┆ 443 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ inn ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 12: ┆ 00: │
│     ┆     ┆ 36  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ers ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 51: ┆ 57: │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ in  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00. ┆ 00. │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ des ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 564 ┆ 523 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ign ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 782 ┆ 312 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i…  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ +00 ┆ +00 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ :…  ┆ :…  │
│ 103 ┆ 263 ┆ 765 ┆ 58  ┆ 1   ┆ 69  ┆ 0   ┆ 65. ┆ 140 ┆ spa ┆ not ┆ 140 ┆ 140 ┆ fal ┆ 2   ┆ 0   ┆ 0.4 ┆ 0   ┆ tru ┆ fal ┆ tru ┆ 202 ┆ 202 │
│ 557 ┆ 480 ┆ 611 ┆     ┆     ┆     ┆     ┆ 0   ┆ 522 ┆ nis ┆ rec ┆ 197 ┆ 197 ┆ se  ┆     ┆     ┆ 777 ┆     ┆ e   ┆ se  ┆ e   ┆ 5-0 ┆ 5-0 │
│ 46  ┆     ┆ 980 ┆     ┆     ┆     ┆     ┆     ┆ 039 ┆ h   ┆ ome ┆ 409 ┆ 409 ┆     ┆     ┆     ┆ 38  ┆     ┆     ┆     ┆     ┆ 9-0 ┆ 9-0 │
│     ┆     ┆ 509 ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆ nde ┆ 7   ┆ 7   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7   ┆ 9   │
│     ┆     ┆ 950 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ d   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 12: ┆ 00: │
│     ┆     ┆ 86  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ at  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 51: ┆ 57: │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ all ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00. ┆ 00. │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 564 ┆ 523 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ han ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 782 ┆ 312 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ten ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ +00 ┆ +00 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ :…  ┆ :…  │
│ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   │
│ 116 ┆ 896 ┆ 765 ┆ 0   ┆ 6   ┆ 108 ┆ 0   ┆ 276 ┆ 169 ┆ eng ┆ I'm ┆ 165 ┆ 165 ┆ fal ┆ 3   ┆ 0   ┆ 0.5 ┆ 0   ┆ tru ┆ fal ┆ fal ┆ 202 ┆ 202 │
│ 635 ┆ 230 ┆ 611 ┆     ┆     ┆ 73  ┆     ┆ 1.0 ┆ 602 ┆ lis ┆ sti ┆ 461 ┆ 461 ┆ se  ┆     ┆     ┆ 625 ┆     ┆ e   ┆ se  ┆ se  ┆ 5-0 ┆ 5-0 │
│ 839 ┆     ┆ 980 ┆     ┆     ┆     ┆     ┆     ┆ 446 ┆ h   ┆ ll  ┆ 600 ┆ 601 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9-0 ┆ 9-0 │
│     ┆     ┆ 872 ┆     ┆     ┆     ┆     ┆     ┆ 6   ┆     ┆ pla ┆ 2   ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7   ┆ 9   │
│     ┆     ┆ 966 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ yin ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 12: ┆ 01: │
│     ┆     ┆ 03  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ g   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 51: ┆ 01: │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ for ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00. ┆ 54. │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ som ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 564 ┆ 538 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 782 ┆ 460 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ine ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ +00 ┆ +00 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ :…  ┆ :…  │
│ 946 ┆ 251 ┆ 765 ┆ 602 ┆ 8   ┆ nul ┆ nul ┆ 182 ┆ nul ┆ eng ┆ Onl ┆ 139 ┆ 139 ┆ tru ┆ 4   ┆ 0   ┆ 0.5 ┆ 0   ┆ tru ┆ fal ┆ fal ┆ 202 ┆ 202 │
│ 971 ┆ 510 ┆ 611 ┆     ┆     ┆ l   ┆ l   ┆ .0  ┆ l   ┆ lis ┆ y   ┆ 482 ┆ 482 ┆ e   ┆     ┆     ┆ 028 ┆     ┆ e   ┆ se  ┆ se  ┆ 5-0 ┆ 5-0 │
│ 3   ┆     ┆ 979 ┆     ┆     ┆     ┆     ┆     ┆     ┆ h   ┆ on  ┆ 752 ┆ 752 ┆     ┆     ┆     ┆ 95  ┆     ┆     ┆     ┆     ┆ 9-0 ┆ 9-0 │
│     ┆     ┆ 712 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ the ┆ 7   ┆ 7   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7   ┆ 8   │
│     ┆     ┆ 909 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sec ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 12: ┆ 03: │
│     ┆     ┆ 52  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ond ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 51: ┆ 09: │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ set ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00. ┆ 34. │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ of  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 564 ┆ 083 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ lev ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 782 ┆ 959 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e…  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ +00 ┆ +00 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ :…  ┆ :…  │
│ 946 ┆ 251 ┆ 765 ┆ 602 ┆ 8   ┆ nul ┆ nul ┆ 182 ┆ nul ┆ eng ┆ Onl ┆ 139 ┆ 139 ┆ tru ┆ 0   ┆ 0   ┆ 0.5 ┆ 0   ┆ tru ┆ fal ┆ fal ┆ 202 ┆ 202 │
│ 971 ┆ 510 ┆ 611 ┆     ┆     ┆ l   ┆ l   ┆ .0  ┆ l   ┆ lis ┆ y   ┆ 482 ┆ 482 ┆ e   ┆     ┆     ┆     ┆     ┆ e   ┆ se  ┆ se  ┆ 5-0 ┆ 5-0 │
│ 4   ┆     ┆ 979 ┆     ┆     ┆     ┆     ┆     ┆     ┆ h   ┆ on  ┆ 752 ┆ 752 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9-0 ┆ 9-0 │
│     ┆     ┆ 712 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ the ┆ 7   ┆ 7   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7   ┆ 8   │
│     ┆     ┆ 909 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sec ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 12: ┆ 03: │
│     ┆     ┆ 52  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ond ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 51: ┆ 09: │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ set ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00. ┆ 34. │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ of  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 564 ┆ 083 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ lev ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 782 ┆ 959 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e…  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ +00 ┆ +00 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ :…  ┆ :…  │
│ 946 ┆ 251 ┆ 765 ┆ 602 ┆ 8   ┆ nul ┆ nul ┆ 182 ┆ nul ┆ eng ┆ Onl ┆ 139 ┆ 139 ┆ tru ┆ 0   ┆ 0   ┆ 0.5 ┆ 0   ┆ tru ┆ fal ┆ fal ┆ 202 ┆ 202 │
│ 971 ┆ 510 ┆ 611 ┆     ┆     ┆ l   ┆ l   ┆ .0  ┆ l   ┆ lis ┆ y   ┆ 482 ┆ 482 ┆ e   ┆     ┆     ┆     ┆     ┆ e   ┆ se  ┆ se  ┆ 5-0 ┆ 5-0 │
│ 5   ┆     ┆ 979 ┆     ┆     ┆     ┆     ┆     ┆     ┆ h   ┆ on  ┆ 752 ┆ 752 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9-0 ┆ 9-0 │
│     ┆     ┆ 712 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ the ┆ 7   ┆ 7   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7   ┆ 8   │
│     ┆     ┆ 909 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sec ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 12: ┆ 03: │
│     ┆     ┆ 52  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ond ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 51: ┆ 09: │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ set ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00. ┆ 34. │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ of  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 564 ┆ 083 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ lev ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 782 ┆ 959 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e…  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ +00 ┆ +00 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ :…  ┆ :…  │
│ 946 ┆ 251 ┆ 765 ┆ 602 ┆ 8   ┆ nul ┆ nul ┆ 182 ┆ nul ┆ eng ┆ Onl ┆ 139 ┆ 139 ┆ tru ┆ 0   ┆ 0   ┆ 0.5 ┆ 0   ┆ tru ┆ fal ┆ fal ┆ 202 ┆ 202 │
│ 971 ┆ 510 ┆ 611 ┆     ┆     ┆ l   ┆ l   ┆ .0  ┆ l   ┆ lis ┆ y   ┆ 482 ┆ 482 ┆ e   ┆     ┆     ┆     ┆     ┆ e   ┆ se  ┆ se  ┆ 5-0 ┆ 5-0 │
│ 6   ┆     ┆ 979 ┆     ┆     ┆     ┆     ┆     ┆     ┆ h   ┆ on  ┆ 752 ┆ 752 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9-0 ┆ 9-0 │
│     ┆     ┆ 712 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ the ┆ 7   ┆ 7   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7   ┆ 8   │
│     ┆     ┆ 909 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sec ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 12: ┆ 03: │
│     ┆     ┆ 52  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ond ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 51: ┆ 09: │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ set ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00. ┆ 34. │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ of  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 564 ┆ 083 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ lev ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 782 ┆ 959 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e…  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ +00 ┆ +00 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ :…  ┆ :…  │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

Проверим, у встречаются ли разные `timestamp_created` у дубликатов:

In [7]:
duplicates.group_by(['author_steamid', 'appid']).agg(pl.col('timestamp_created').n_unique())

shape: (6, 3)
┌───────────────────┬─────────┬───────────────────┐
│ author_steamid    ┆ appid   ┆ timestamp_created │
│ ---               ┆ ---     ┆ ---               │
│ i64               ┆ i64     ┆ u32               │
╞═══════════════════╪═════════╪═══════════════════╡
│ 76561198087296603 ┆ 896230  ┆ 2                 │
│ 76561198134172548 ┆ 207000  ┆ 1                 │
│ 76561198069244336 ┆ 253370  ┆ 1                 │
│ 76561197961949171 ┆ 1336840 ┆ 2                 │
│ 76561197971290952 ┆ 251510  ┆ 1                 │
│ 76561198050995086 ┆ 263480  ┆ 1                 │
└───────────────────┴─────────┴───────────────────┘

Некоторые дубликаты отличаются не только recommendationid, но и количеством лайков (`votes_up`), при чем

In [ ]:
reviews_clean = (
    reviews_df
    .sort(['author_steamid', 'appid', 'timestamp_created', 'votes_up'], descending=[False, False, True, True])
    .unique(subset=['author_steamid', 'appid'], keep='first')
)

assert len(reviews_clean) == len(reviews_clean.unique(subset=['author_steamid', 'appid']))
print(f"Очистка успешна! Осталось {len(reviews_clean):,} записей.")

Очистка успешна! Осталось 1,048,140 записей.